// src/components/DarkModeToggle.svelte
<script>
  let title = "off";

  const toggle = (e) => {
    e.preventDefault();
    const isOn = title == "on";
    if (isOn) {
      document.documentElement.classList.remove("dark");
    } else {
      document.documentElement.classList.add("dark");
    }
    title = isOn ? "off" : "on";
  };
</script>

<p>
    <a href="#" on:click={toggle}>
        {title}
    </a>
</p>

// src/components/nav/DarkModeToggle.tsx
import { Component } from "preact";

interface State {
  on: boolean;
}

export default class DarkModeToggle extends Component<{}, State> {
  constructor(props) {
    super(props);

    let val = localStorage.getItem("dark-mode");

    if (!val && window.matchMedia("(prefers-color-scheme: dark)").matches) {
      val = "1";
    }

    this.state = {
      on: val == "1",
    };
  }

  applyState = (on: boolean) => {
    if (on) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }

    localStorage.setItem("dark-mode", on ? "1" : "0");
    console.log("val is now", localStorage.getItem("dark-mode"));
  };

  toggle = (e) => {
    e.preventDefault();

    const newOn = !this.state.on;

    this.applyState(newOn);

    this.setState({
      on: newOn,
    });
  };

  render() {
    return (
      <a href="#" onClick={this.toggle}>
        Dark Mode {this.state.on ? "On" : "Off"}
      </a>
    );
  }
}
